languageCode = "en-us"
title = "Vertigo Band"
baseURL = "https://vertigo.band"
theme = "massively"
googleanalytics = "UA-127408872-1"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]



[params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"
  backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Vertigo - Versión Español"


