title = "Vertigo Band"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
  weight = 2
  name = "News"
  url = "/news"

  [[menu.header]]
    weight = 3
    name = "Releases"
    url = "/releases"

  [[menu.header]]
    weight = 4
    name = "Band"
    url = "/band"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
   weight = 1
   name = "<i class='fa fa-2x fa-facebook'></i> Facebook"
   url = "https://www.facebook.com/VertigobandaCR/"

  [[menu.footer]]
    weight = 2
    name = "<i class='fa fa-2x fa-instagram'></i> Instagram"
    url = "https://www.instagram.com/vertigobandacr/"

  [[menu.footer]]
    weight = 3
    name = "<i class='fa fa-2x fa-at'></i> Bandcamp"
    url = "https://vertigocr.bandcamp.com/"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Vertigo - ONE"
    subtitle = "Available in all major digital platforms."

  [params.wrapper]
    enable = true
    title = "Vertigo - One "
    italic = "Released on May 24th, 2018"
    paragraph = "We are really excited to announce our first album, ONE, was released to all major digital platforms on May 24th, 2018. The album was recorded at Bushido Audio Productions from February  to April of 2018. "

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Rock with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "A brief history about us"
    content = "Vertigo was formed during 2013 by Alex and Claudio. For work reasons, Alex moved to Poland, which lead to a full stop of the band. In 2017 Alex returned to Costa Rica, and after finding new band members, Vertigo resumed playing and working on original material. Since then Vertigo has been fully alive, doing presentations in different venues all around Costa Rica."
#    [params.feature.button]
#      caption = "View Next Dates"
#      url = "#"

  [params.call]
    enable = true
    title = "Follow us on social media."
    paragraph = "To get the most up to date news and know what we are doing folow us on social media "

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Contact Info"
      address = "San Jose, Costa Rica"
      email = "Email: vertigobandacr@gmail.com"
      phone = "Phone: +506 87 09 11 99"
#    [params.contact.gmaps]
#      title = "We Also Count in Google Maps"
